language: python
python:
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
install:
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then pip install 'Jinja2<2.7' --use-mirrors; fi" # Jinja2 2.6 is last version which supports Python 3.2; required by Sphinx
  - "pip install Sphinx --use-mirrors"
  - "pip install Tinkerer --use-mirrors"
  - "pip install . --use-mirrors"
before_script:
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then 2to3 -w -n test; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then 2to3 -w -n test; fi"
script:
  - "cd test"
  - "nosetests"

