language: python
dist: xenial
sudo: false
python:
  - "3.8-dev"
  - "3.7"
  - "3.6"
  - "3.5"
  #- "pypy"  # travis builder issues?
branches:
  only:
    - develop
install:
  - "pip install sphinx-testing Tinkerer" # required for tests
  - "pip install ."
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then pip install codecov check-manifest flake8; fi"
script:
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then check-manifest; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then flake8; fi"
  - "pushd doc"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then make html; fi"
  - "popd"
  - "pushd test"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then nosetests --with-coverage; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION != '3.7' ]]; then nosetests; fi"
  - "popd"
after_success:
  - "pushd test"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then codecov; fi"
  - "popd"
