language: python
python:
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
  - "pypy"
branches:
  only:
    - develop
install:
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then pip install 'Jinja2<2.7'; fi" # Jinja2 2.6 is last version which supports Python 3.2; required by Sphinx
  - "pip install Sphinx==1.1.3" # Sphinx 1.2b1 is broken; https://bitbucket.org/birkenfeld/sphinx/issue/1160/citation-target-missing-assertionerror
  - "pip install Tinkerer"
  - "pip install ."
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install coveralls; fi"
before_script:
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then 2to3 -w -n test; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then 2to3 -w -n test; fi"
script:
  # only test documentation and run coverage for one python version
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then cd doc; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then make html; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then cd ..; fi"
  - "cd test"
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then coverage run --source=sphinxcontrib.bibtex `type -p nosetests`; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION != '2.7' ]]; then nosetests; fi"
after_success:
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then coveralls; fi"

