language: python
python:
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"
branches:
  only:
    - develop
install:
  - "pip install Tinkerer" # Tinkerer is required for tests
  - "pip install ."
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install coveralls; fi"
before_script:
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then 2to3 -w -n test; fi"
script:
  # only test documentation and run coverage for one python version
  - "pushd doc"
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then make html; fi"
  - "popd"
  - "pushd test"
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then coverage run --source=sphinxcontrib.bibtex `type -p nosetests`; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION != '2.7' ]]; then nosetests; fi"
  - "popd"
after_success:
  - "pushd test"
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then coveralls; fi"
  - "popd"
